method: grid

parameters:
  model:
    parameters:
      lambda_dmeasure:
        values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

metric: 
  goal: maximize
  name: test0_c0_MulticlassAccuracy